#!/usr/bin/env bash
# A script to get the required dependencies for fcatalog server.
# Run this script when you have internet connection, and python3 installed.
# This script will fill the dep/ directory with all the required stuff for
# offline installation.

# Stop on any error:
set -e

###################################
# Get Virtualenv script:
###################################

# Version of virtualenv:
VERSION=13.1.2
# Virtualenv tgz filename:
VENV_TGZ=virtualenv-$VERSION.tar.gz
VENV_DIR=virtualenv-$VERSION

# Environment name:
INITIAL_ENV=temp_env

# Python3 interpreter:
PYTHON=$(which python3)

# URL of pypi to get virtualenv package:
URL_BASE=https://pypi.python.org/packages/source/v/virtualenv

printf "\nDownloading virtualenv:\n\n"

# Download virtualenv:
curl -O $URL_BASE/$VENV_TGZ

# Create the dep directory:
mkdir -p dep/

cp $VENV_TGZ dep/
# Open VENV_TGZ:
tar xzf $VENV_TGZ
# Remove virtual env if existent:
rm -rf $INITIAL_ENV

# Create an initial virtual env:
$PYTHON $VENV_DIR/virtualenv.py $INITIAL_ENV

# The tgz file is not needed here anymore. We delete it:
rm -rf $VENV_TGZ
# The virtualenv directory is not needed here anymore:
rm -rf $VENV_DIR

####################################
# Create an fcatalog wheel:
####################################
printf  "\nCreating an fcatalog wheel\n\n"
# Install wheel into pip.
$INITIAL_ENV/bin/pip install wheel

cd fcatalog

# Remove dirs from a previous build, if existent:
rm -rf build/
rm -rf dist/
rm -rf fcatalog.egg-info/


# Create a wheel:
../$INITIAL_ENV/bin/python setup.py bdist_wheel

cd ..

mkdir -p dep/packages

# Copy the resulting wheel into dep:
cp -R fcatalog/dist/*.whl dep/packages/


####################################
# Get required python packages:
####################################

printf "\nGetting required python packages:\n\n"


# Downloads packages
$INITIAL_ENV/bin/pip install --download dep/packages -r requirements.txt

# Remove the temporary python environment:
rm -rf $INITIAL_ENV

set +e
